# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Ken Gallo
title: Principal Security Architect & Engineer
#email: 
#website: 

# Dark Mode (true/false/never)
darkmode: false

# Social links
#twitter_username: facespics
#github_username:  sproogen
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
#instagram_username: jameswgrant
linkedin_username: kengallo
# xing_username: jekyll
# pinterest_username: jekyll
#youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
- title: itsgoingto.be
  icon: fas fa-globe
  url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Experienced Security Architect that delivers effective and efficient security solutions. Expert in a range of fields including: cloud security, cryptography, web application security, and incident handling. CISSP & CCSP, many SANS certifications, AWS Solutions Architect, and others.

content:
  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: GE HealthCare
        link: gehealthcare.com
        # link_text: gehealthcare.com
        sub_title: Principal Information Security Engineer
        caption: March 2023 - Present
        description: | # this will include new lines to allow paragraphs
            Details available upon request 

      - layout: left
        title: General Electric
        link: ge.com
        # link_text: ge.com
        sub_title: Principal Information Security Engineer
        caption: March 2015 - March 2023
        quote: >
          Information Security Engineer and Architect for one of the world's leading aviation, power, and renewable energy companies. 
        description: | # this will include new lines to allow paragraphs
            - Designed and implemented a massive and innovative PKI (Public Key Infrastructure). The system has issued millions of certificates while saving the company millions of dollars. It enables several services, including an advanced GE-built VPN relied upon by >200,000 users worldwide. 
            - Architected and deployed a highly available certificate automation service running on Kubernetes. The solution cut down processing time from hours to seconds, saving the company substantial costs while improving security.
            - Architected and oversaw development of API services to automate certificate management. Transformed development processes to Agile methodology and CI/CD workflows. The results are robust and scalable APIs that have delivered millions of certificates with >99.9% reliability. 
            - Helped to architect and build a cloud file encryption solution relied on by >500,000 daily users. The service runs in AWS, encrypts >12 million files daily, and has run for nearly 3 years without losing a single key. It is critical to saving GE millions of dollars per year by enabling powerful new collaboration tools that speed up business. 
            - Designed a Key Management Service that will securely generate and protect cryptographic keys across public cloud and internal platforms. The solution, based on HashiCorp Vault, can handle 100x the load of our earlier service while providing an innovative Encryption-as-a-Service that makes good encryption easy for application developers. The service will enable the company to run sensitive and secret applications around the world with full security and regulatory compliance. 
            - Created security policies and processes that provide business flexibility while ensuring best practices and security. 
            - Mentored and lead less experienced teammates to deliver successful projects.

      - layout: left
        title: Gallo Security, Inc.
        link: 
        # link_text: 
        sub_title: Owner and Principal Consultant
        caption: Jun 2007 - Dec 2015
        quote: >
          Information security consultant for a variety of regional and global businesses. 
        description: | # this will include new lines to allow paragraphs
            -  A long-term security design and architecture project at a Fortune 10 company. Oversaw more than 40 high-security network enclaves spread across the United States. The enclaves enabled the business to provide services to the military and fulfill multi-billion dollar contracts. 
            -  PKI consulting at a mid-sized logistics company. Identified an impending collapse of their systems and helped the client avert a catastrophic outage.
            -  Helped a major company design and implement software to monitor firewall rules, analyze risk, and manage changes across hundreds of firewalls.
            -  Designed a massive data analytics cluster service for a clinical testing company. Using Apache Hadoop, and running in AWS, the new system performed >100x faster than the client's old system. The analysis time shrunk from days to minutes, permitting the client to gain new insights and business.
            -  Security architecture review and multiple ISO 27001/2 audits for several mid-size businesses.
            -  Incident handling, forensics, and risk assessments for a university after a significant event.

      - layout: left
        title: Convergys
        link: 
        # link_text: 
        sub_title: Information Security Architect
        caption: Apr 2006 - Jun 2011
        quote: > 
        description: | # this will include new lines to allow paragraphs
            Information security architect responsible for the security and compliance of several high-availability PCI platforms. The platforms provided critical services for several large banks, a national credit card company, small businesses, and a cloud service.

      - layout: left
        title: Great American Insurance
        link: 
        # link_text: 
        sub_title: Senior Security Engineer 
        caption: Jun 2003 - Apr 2006
        quote: > 
        description: | # this will include new lines to allow paragraphs
            Security design and operations for this Fortune 500 insurance company. Performed firewall management, conducted vulnerability assessments, and ran critical IAM and security services.

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Miami University 
        caption: 
        sub_title: BSc Business School (MIS)
        quote: >
          Miami University, established in 1809, is ranked among the top 50 national public universities by U.S. News & World Report. As an original Public Ivy, Miami provides Ivy League-quality education at a public school.
        description: | # this will include new lines to allow paragraphs
          Minors: International Business and Spanish

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in networks and software engineering some of my other interests and hobbies are:
      - Photography
      - Travel

      ![Trees](/modern-resume-theme/images/landscape-trees.jpg "Trees")

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
